### ISSUE TITLE
Zhe sa verbal compounds?

### ISSUE THREAD

**Issue by solmsdorf** [tibetan-nlp/annotation-docs#1]
Should we make use of the UD compound relation for honorific verbal compounds (_zhe sa_, e. g. _sku gshegs_)?

**Comment by heacu** [comment]
Clarifying, here's the example from Mila page 11a:

> ཡབ་མི་ལ་ཤེས་རབ་རྒྱལ་མཚན་སྐུ་གཤེགས་

Sure, let's try using the UD `compound` relation for these cases. I've added `compound` to the annotation configuration, and edited this particular example so that སྐུ་ now depends on གཤེགས་ via the `compound` relation. At the moment the relation is defined conservatively to only allow a `NOUN` to depend on a `VERB`.

I'll leave this issue open until the documentation is updated.

**Comment by heacu** [comment]
Documentation updated: https://tibetan-nlp.github.io/lim-annodoc/#honorific-verbal-compounds

**Comment by heacu** [comment]
Nathan Hill points out that this policy is inconsistent with our proposed approach to light verbs (see https://github.com/tibetan-nlp/lim-annodoc/issues/8), and therefore advises treating the honorific noun as an `arg2`, similar to the noun in a light verb construction.

**Comment by heacu** [comment]
I changed the examples of honorific verbs on Mila page 11a to use `arg2` instead of `compound`. Closing issue.

**Comment by solmsdorf** [comment]
Re-opening the issue (how?):

Should we use `arg2` or rather `arg2:lvc` for honorific constructions?

**Comment by heacu** [comment]
click the "Reopen and comment" button online under your comment to reopen the issue.

**Comment by heacu** [comment]
Let's just use `arg2:hon` to mark honorifics. That way we can more easily distinguish them from typical light verb constructions.

**Comment by solmsdorf** [comment]
Many thanks. Sounds good to me.

There is no "Reopen and Comment" button, only "Comment" (which feels odd on a closed issue). Maybe only the Owner can reopen issues?

Edit: Only the person who closed the issue can reopen it.
