### ISSUE TITLE
Annotation of modal verbs?

### ISSUE THREAD

**Issue by solmsdorf** [tibetan-nlp/annotation-docs#4]
Should the relation from main verb to modal verb—e. g. _dgos_ ("need to"), _nus_ ("able to"), _'dod_ ("want to")—in Tibetan be interpreted as `aux`or `argcl` (UD says: _Modal verbs_ may count as auxiliaries in some languages (English). In other languages their behavior is not too different from the main verbs and they are thus tagged VERB (http://universaldependencies.org/u/pos/all.html#al-u-pos/AUX))?

E. g. from Mila 11b: _a khu dang a ne la ngo mi tsha ba cig byed dgos_

**Comment by heacu** [comment]
The page that you cite refers to POS-tagging, not dependency relations. The TIDC project tagged modals as `v.aux`, but concluded that this was a mistake.

> This tag is used for auxilliary verbs. By this we understand only those verbs that show no morphological stem variation and may occur directly after another verb stem. The words we tag with this tag are: ཐག་, དགོས་, ནུས་, མོད་, འདོད་, ཤེས་, སྲིད་, ཤེས་, རན་, གྲགས་, ཐང་, and ཕོད་. Note that this set is far fewer than the total number of verbs that might be considered auxiliary verb in classical or modern Tibetan. In fact, we now feel that it was a mistake the give these tags a separate encoding, instead they should have been tagged on the basis of their syntax (e.g. mi [neg] nus [v.pres.v.fut]) and the question of auxiliation and other syntactic uses of verb stems in Tibetan addresssed systematically in a future project. However, once we arrived at this understanding it was inconvenient to change our approach. 

*LIM* is that future project, where we have replaced `v.aux` with `VERB`. There is no information lost, however, because in terms of syntactic dependencies we can make modals depend as [`aux`](http://universaldependencies.org/u/dep/aux_.html) on the main verb.

The alternative, as you suggest, would be to make the main verb depend as `argcl` on the modal, thus reversing the dependency. I disprefer this approach for two reasons. First, the main verb is the "content word", and so having the modal as the dependent seems to better fit the spirit of UD, and second, these modals do not otherwise introduce an argument structure of their own. For example, they do not introduce a new `arg1` that is distinct from the `arg1` of the main verb.

So go ahead and use `aux`. When you corrected this example, then I will copy it to the documentation and close this issue.

**Comment by solmsdorf** [comment]
Perfect, we will thus use the `aux` relation for modal verbs. The above-mentioned example is corrected (it is from Mila 12a not 11b!), issue can be closed.
