### ISSUE TITLE
Tagging of End of Quotation (zhes bya ba)?

### ISSUE THREAD

**Issue by solmsdorf** [tibetan-nlp/annotation-docs#5]
How should we annotate _(zhes) bya ba/zer ba_ "thus said/so-called" (end of quotation)? Like a copula?

E. g. from Mila 11a: _zhing skal (`arg1`?) bre pe stan chung bya ba (`cop`?)_

**Comment by heacu** [comment]
There are several issues here that need to be untangled.

1. What to do about the (optional) quotative verb _zhes_ in _zhing skal bre pe stan zhes chung bya ba_? We could consider it a content word and so the `argcl` of _bya ba_, with _bre pe stan chung_ an argument of _zhes_. Or, we could consider _zhes_ a function word, like a complementizer that introduces an embedded clause. _bre pe stan chung_ would then be an argument of _bya ba_, and _zhes_ would depend on _bre pe stan chung_, perhaps via [`mark`](http://universaldependencies.org/u/dep/mark.html), which however is intended to introduce finite subordinate clauses.

1. What argument role does _zhing skal_ get? We agreed in earlier discussion that it should be an argument of _bya ba_ but should it be `arg1` as suggested above or `arg2`? Given that an agent (the speech source) is in principle possible - if not in this exact construction - then I would label it an `arg2`.

1. What argument role does the head of the reported speech phrase get? In the version of the sentence without _zhes_, I would label _bre pe stan chung_ an `arg3`.

There is one advantage of treating _zhes_ as a function word, which is that the sentences with _zhes_ are treated the same as the sentences without it, with regard to the key dependency relations. But if this does disservice to the syntax (for example, if there is evidence that constructions with and without _zhes_ behave differently), then a uniform analysis might not be advisable.

I suggest that we proceed with a tentative approach, and revisit the issue later when we have a catalogue of cases to consider. It is worth following much of this up on the UD list, but I think we should wait until we have more and varied examples and have also translated them so that our questions will be more easily understood.

**Comment by solmsdorf** [comment]
We are rather uncertain about the qualification of _zhes_ as a verb. Could someone please elaborate on this (in excess of the short interpretation in the SOAS system: http://larkpie.net/tibetancorpus/node/113706)? Etymologically this may be the case, however, it's usage suggest something else; it's allomorphs _ces_ and _zhes_ depend on the final of the preceding syllable, which also bespeaks a qualification as a function word.

That is to say, we definitely lean towards a qualification of _zhes_ as a function word. Given the high degree of its optionality we would rather ignore it in annotating verb dependencies.

However, more examples are needed and will be uploaded here.

**Comment by heacu** [comment]
Good point about the allomorphs.

So as we collect more attestations for inclusion here, let's proceed in the meanwhile on the assumption that _zhes_ / _ces_ will depend as `mark` on the head of the speech complement.

We need not indicate the `mark` relationship yet, since we aren't linking to other `mark`. Technically, this violates our principle that _Every verb should be annotated and no verb should be ignored_, but since the verbhood of _zhes_ / _ced_ is being called into question, this seems like a legitimate exception.

**Comment by heacu** [comment]
Examples of _zhes_ copied in from Slack for the documentation via Samyo: 

1. _gral pa `arg1` rnams snyan gsan `argcl` par zhu `argcl` zhes brjod nas_ “she said: ‘elders, please listen closely’” (11a)
2. _a mas `arg1` … pha shul `arg2` bus `arg1` ‘dzin `argcl` du ‘jug `argcl` par zhu `argcl` byas pas_ “my mother said: ‘I ask you to let my son take possession of his patrimony’” (11a)
3. _ a ma ni `arg1` … da gzigs pa’i dus `obl` la bab `argcl` gda’o `aux` zer_ “my mother said: ‘the time has come that you look [upon us]‘” (11b)

Again, we think that _zhes_ is not a verb but a suffix to mark the end of quotation.

**Comment by solmsdorf** [comment]
Room for further examples:

4. _gung thang gi lhun grub ’gron khang bya bar_ "in a [place] called _Lhun grub Guest House_ in Gung thang" (13b)

**Comment by heacu** [comment]
@nikolaisolmsdorf If you are okay with https://tibetan-nlp.github.io/lim-annodoc/#quotatives, then I'll close this issue. If you want to debate the POS tag for _zhes_ / _ced_, then please take that up on Slack in the #tagging channel where Nathan will see it.

**Comment by solmsdorf** [comment]
@torma Many thanks, the entry in the lim-annodoc is fine, however, how do we deal with so-called/named etc. usages of _zhes_? Cf. the above-mentioned example from Mila 11a: 

_zhing skal bre pe stan chung bya ba_

For the time being, we annotated it like this: _zhing skal `arg1` bre pe stan chung `arg2` bya ba_

Still, we are not sure if this is a reasonable approach.

**Comment by heacu** [comment]
Hi -

It is worth noting that this example shouldn't even be on page 11a. If we had page 10b, it would appear on 10b, since our protocol is to reach greedily across the page until the next sentence boundary. Below is the full sentence:

> ཨ་མ་ལ་ཕ་མས་བྱིན་པའི་ཞིང་སྐལ་བྲེ་པེ་སྟན་ཆུང་བྱ་བ་མིང་མི་སྙན་རུང་སྟོན་ཐོག་ཡོང་པ་ཅིག་ཡོད་པ་དེ།

Which Andy Quintman translates as follows:

> At that time there was a field given to my mother by her parents as her inheritance, known by the unpleasant name Trepé Tenchung5 (Little Boot Sole) but producing an excellent harvest.

If it didn't require modifying all of the word offsets, I would be tempted to remove the sentence from the page. Instead, for the time being we can leave the partial sentence, which you have analysed like so:

<img width="656" alt="bya_ba" src="https://user-images.githubusercontent.com/1461961/32233061-7014c620-be51-11e7-83c0-56f41bdc8b54.png">

The problem I have with this analysis is that it treats the clauses as entirely independent from each other, whereas the relations between them need to be indicated. For example, _snyan_ should be linked as `advcl` to `yong pa`, since a _rung_ clause adverbially modifies another clause. Even after this relation is inserted, there is no link between _zhing skal ... bya ba_ and the remainder of the sentence, which seems odd. Is it possible that the correct analysis is:

(ཨ་མ་ལ་ཕ་མས་བྱིན་པའི་ཞིང་སྐལ་)<sub>1</sub> (བྲེ་པེ་སྟན་ཆུང་བྱ་བ་)<sub>2</sub> (མིང་མི་སྙན་རུང་སྟོན་ཐོག་ཡོང་པ་)<sub>3</sub> ཅིག་ཡོད་པ་དེ།

In which _zhing skal_ is actually `arg1` to _yod pa_, and clauses 2 and 3 are modifiers (say, post-nominal headless relative clauses) of 1. If so, then _bya ba_ would have only one argument, _bre pe stan chung_, which I would mark as `arg2`.

Ed

**Comment by nh36** [comment]
Hey folks. The reason for seeing zhes as a verb is purely morphological. zhes is a past, zhe is a present/future. All the things that can come after verbs like -na, and -pa-dang, can come after zhes. It is true that we have some allomorphy here and that this is unique to this verb, but so what, it is still a verb. Also, as discussed in this chain, other verbs like byed, and bgyid, can function in a similar way, and in their cases no one would suggest that they are not verbs. So, if we already know verba dicendi form a certain class and byed and bgyid are members of this class, what is the harm in seeing zhes as another example of this type? If you want examples, they can be found in the training corpus by looking at zhe or ces-pa, etc.

**Comment by heacu** [comment]
Ok, based on the discussion above and a conversation with @nikolaisolmsdorf today, we will close this issue having resolved for now the following:

- We retain `VERB` as the POS tag for _zhes_ in the construction _zhes bya ba_.
- We treat _zhes_ non-predicatively and link it via the `mark` relation. Since we haven't got on to marking `mark` yet, for the time being we simply ignore _zhes_ in our annotations.
