### ISSUE TITLE
''dug' as a light verb?

### ISSUE THREAD

**Issue by solmsdorf** [tibetan-nlp/annotation-docs#7]
Can  _'dug_ function as a light verb, similar to _yod_ (cf. https://github.com/tibetan-nlp/lim-annodoc/issues/3)? 

E. g. from Mila 11b: _gzhan (`arg1`) rnams kyang shugs ring (`arg2`) nar nar 'dug (`V`)_ "the others, too, sighed deeply".

=> _'dug_ may at times also be interpreted as a `cop` (= testimonial use of _'dug_, cf. Hill 2013)! Which may also be the case here.

E. g. from Mila 55b: _yi ge (`N`=`arg1`) rnams khra lam me (`A`) 'dug pa (`cop`)_ "the letters were clear".

**Comment by heacu** [comment]
Regarding copular uses of _'dug_ with adjectival predication, we can analyze them as we analyze copular uses of _yin_. So _yi ge_ is not `arg1`, at least not of the `VERB`. Rather, it is an argument of the `ADJ`. _'dug pa_ therefore depends on _rnams khra lam me_ via the  [`cop`](http://universaldependencies.org/u/dep/cop.html) relation.

I realize that the example is on Mila 55b, but if you can annotate that example anyway in BRAT, then I can copy it into the documentation.

**Comment by solmsdorf** [comment]
Ok, copula use of _'dug_ should be implemented. The above-mentioned example cannot be annotated that way, it's not possible to draw relation-arcs from an `A`.

**Comment by heacu** [comment]
I had configured the `cop` relation to only target words with the `AUX` POS tag, like _yin_. I have now broadened the relation to target any `VERB`. Most verbs can't be copulas, but _'dug_ can.

You should now be able to annotate the example on Mila 55b. You won't be able to make the `NOUN` depend on the `ADJ`, but that's okay, because for the time being we are only annotating verbs.

**Comment by heacu** [comment]
Can I close this issue? Can you do what you need to do?
